version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: pg-gestao-financeira
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gestao_financeira
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
